* Tools I use
<2015-08-06 Thu>

fzf: Fuzzy Finder
tmux
Emacs with Prelude setup: prasincs/emacs-prelude repository
zsh with oh-my-zsh

* Resources on some Fundamentals

+ How Keyboard I/O works
http://unix.stackexchange.com/questions/116629/how-do-keyboard-input-and-text-output-work/116630#116630

* Tmux
** References
https://robots.thoughtbot.com/a-tmux-crash-course
**  Switching directly to windows from anywhere
ctrl-b s to get list of all running tmux sessions, Press Space to get list of all windows in sessions


** Tmuxinator

- Creating New: =tmuxinator new <name>=

** FInding window

- Ctrl-b f <window name>
- Ctrl-b w [Lists all the windows]
- Ctrl-b s [Lists all the sessions] and on pressing Space, expands to windows

** Fullscreen
:resize-pane -Z

If you switch to another pane, it will minimize itself
** Color palette
http://superuser.com/questions/285381/how-does-the-tmux-color-palette-work

Listing available colors in tmux

#+BEGIN_SRC
for i in {0..255} ; do
    printf "\x1b[38;5;${i}mcolour${i}\n"
done
#+END_SRC

** Copying with mouse
Press Option for selecting -- no more need for switching to copy mode, etc
* FZF

** Using the finder

CTRL-J / CTRL-K (or CTRL-N / CTRL-P) to move cursor up and down
Enter key to select the item, CTRL-C / CTRL-G / ESC to exit
On multi-select mode (-m), TAB and Shift-TAB to mark multiple items
Emacs style key bindings
Mouse: scroll, click, double-click; shift-click and shift-scroll on multi-select mode


** Searching for items using ag and filtering

ag "tmux" | fzf


** Allowing extended search/selection

Add the following environment variable

export FZF_DEFAULT_OPTS=--extended


* Perl

** Oneliners printing regex matches

For example: for printing the IP address for a certain interface.

ifconfig | grep -A1 eth1 | perl -lne 'print $1 if /inet addr:(\S+)/'

* Shell (Bash/Zsh)

** Zsh

- Uses zle instead of readline which is lot more powerful

Resources:
+ Reference Card: http://www.bash2zsh.com/zsh_refcard/refcard.pdf
+ http://zshwiki.org/home/zle/bindkeys

*** Keyboard Macros

Although keyboard macros don't work in ZSH in the same way as they do in
bash, there are still ways to make it work. I was able to find and modify
a script from http://enki-tech.blogspot.fr/2012/08/zsh-macros.html

to get somewhat workable flow for OSX setup, there are some very specific
changes that OSX makes to mktemp that weren't accomodated in the script

And, you can use =MX= to execute the last macro as oppose to =e= which is
mapped to emacs for some reason on my machine.


*** Key Bindings

https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh

Finding all the keybindings currently in the shell

=bindkey -L=

To read the keybinding for some key combination.. use the =read= command.

#+BEGIN_SRC
read
#+END_SRC
And press F10, to get

#+BEGIN_SRC
^[[21~
#+END_SRC

And so on.

You can use to map particular key sequences to shell functions. For example,
if you want to map =M-m= to copy the previous word, you can do that using
#+BEGIN_SRC
bindkey "^[m" copy-prev-shell-word
#+END_SRC

*** Removing duplicates from history

awk -i inplace '!x[$0]++' ~/.zsh_history

** Bash

*** Style Guides

http://redsymbol.net/articles/unofficial-bash-strict-mode/

*** Keyboard Macros

Unfortunately zsh doesn't seem to support this

You can add a keyboard macro by typing C-x ( <commands> C-x )
and then replay it using C-x e

*** Editing

http://www.scribd.com/doc/985254/Bash-Emacs-Editing-Mode-readline-Cheat-Sheet

** Deleting words

M-d -> delete the next word |delete
C-w -> delete the last word delete|


** Fail on first non-zero exit
Start the script with =/bin/bash -e=

** Get non-zero status if one of the pipe commands fails
=set -o pipefail=

* Golang
http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/

** Setting up Cross compiling

Go to where go source is. Generally at /usr/local/go/src

Then compile for the target.

sudo GOOS=linux GOARCH=386 CGO_ENABLED=0 ./make.bash

** Profiling & Benchmarking
go test -bench=. -cpuprofile=cpu.out
go test -bench=. -memprofile=mem.out
* Git
** Get to root level

git config --global alias.root "rev-parse --show-toplevel"

Then you can use git root to go to the top directory from anywhere
** Branching Model
http://nvie.com/posts/a-successful-git-branching-model/
* Apt
** Finding more about the package repository
apt-cache madison <packagename>

will show you all the available package versions in the repositories.
* Byobu
https://gist.github.com/jshaw/5255721
* Networking
- Latency times between large cities
https://wondernetwork.com/pings/

* Latency
http://computers-are-fast.github.io/
* OSX
** Making a RAM Disk
Size => Size of Disk in MB * 2048
diskutil erasevolume HFS+ 'RAM Disk' `hdiutil attach -nomount ram://8388608`
* Clojure
;; Reload everything
(require '[clojure.tools.namespace.repl :refer [refresh]])
(refresh)
* Ghostscript
Reducing the size of pdf without sacrificing too much quality
gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -sOutputFile=output.pdf input.pdf
* VS Code
- Search for files by name = > Cmd+P or Ctrl+P
- You can put   "proxy": "http://localhost:8080" in package.json to avoid CORS issues while developing (https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md)
* Terminator

Documentation: https://wiki.archlinux.org/index.php/Terminator
These are for XMonad setup

Ctrl+Shift+X => Focus screen
F11 Toggle fullscreen
Ctrl + Shift + O Split terminals horizontally
Ctrl + Shift + E Split terminals vertically
Ctrl + Shift + W Close current Panel
Ctrl + Shift + T Open new tab (Doesn't work in focus mode)
Alt + ↑ Move to the terminal above the current one
Alt + ↓ Move to the terminal below the current one
Alt + ← Move to the terminal left of the current one
Alt + → Move to the terminal right of the current one
* Firefox beta
download tarball and run in ~/firefox for linux, installing via package managers didn't work well
* Java hackery
Finding all the classes in jar files
https://gist.github.com/nivag/5881687
* Xmonad basics
The default modifier key is 'alt'. Default keybindings:

-- launching and killing programs
mod-Shift-Enter  Launch xterminal
mod-p            Launch dmenu
mod-Shift-p      Launch gmrun
mod-Shift-c      Close/kill the focused window
mod-Space        Rotate through the available layout algorithms
mod-Shift-Space  Reset the layouts on the current workSpace to default
mod-n            Resize/refresh viewed windows to the correct size

-- move focus up or down the window stack
mod-Tab        Move focus to the next window
mod-Shift-Tab  Move focus to the previous window
mod-j          Move focus to the next window
mod-k          Move focus to the previous window
mod-m          Move focus to the master window

-- modifying the window order
mod-Return   Swap the focused window and the master window
mod-Shift-j  Swap the focused window with the next window
mod-Shift-k  Swap the focused window with the previous window

-- resizing the master/slave ratio
mod-h  Shrink the master area
mod-l  Expand the master area

-- floating layer support
mod-t  Push window back into tiling; unfloat and re-tile it

-- increase or decrease number of windows in the master area
mod-comma  (mod-,)   Increment the number of windows in the master area
mod-period (mod-.)   Deincrement the number of windows in the master area

-- quit, or restart
mod-Shift-q  Quit xmonad
mod-q        Restart xmonad
mod-[1..9]   Switch to workSpace N

-- Workspaces & screens
mod-Shift-[1..9]   Move client to workspace N
mod-{w,e,r}        Switch to physical/Xinerama screens 1, 2, or 3
mod-Shift-{w,e,r}  Move client to screen 1, 2, or 3

-- Mouse bindings: default actions bound to mouse events
mod-button1  Set the window to floating mode and move by dragging
mod-button2  Raise the window to the top of the stack
mod-button3  Set the window to floating mode and resize by dragging
* Wget
** Downloading recursive with follow links
wget -b -o wget.log --level=10 --recursive --convert-links --random-wait --exclude-domains twitter.com,gravatar.com -H --domains blog.acolyer.org adriancolyer.files.wordpress.com https://blog.acolyer.org
* Scanning
xsane exports to PNM
** Combine pnm files to pdf

needs graphicsmagick

/usr/bin/gm convert *.pnm output.pdf
