# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ruby git gem)
source $HOME/.profile
source $ZSH/oh-my-zsh.sh

# Customize to your needs...
source ~/.rvm/scripts/rvm 
rvm use 1.9.2 &> /dev/null
export CLASSPATH="$CLASSPATH:$HOME/.lein/self-installs/leiningen-1.7.1-standalone.jar"
source /usr/local/bin/virtualenvwrapper.sh
EDITOR=vim
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/lib:/opt/oracle/instantclient_11_2"

alias rake='noglob rake'

HISTSIZE=5000 # session history size
SAVEHIST=1000 # saved history

PATH=$PATH:/sbin:$HOME/.rvm/bin # Add RVM to PATH for scripting
ANDROID_SDK_DIR=$HOME/code/sdk/android-sdk-linux_x86

PATH=$HOME/depot_tools:$PATH:$ANDROID_SDK_DIR/tools:$ANDROID_SDK_DIR/platform-tools
